#!/usr/bin/env python3
"""Convert an ASCIInator HTML export into site/js/ascii-scene.js.

The export is ~1MB: a <pre> where every character sits in its own coloured
<span>, plus an embedded woff2. Putting that in the page would mean ~30k DOM
nodes, so instead we pull out the two things a canvas renderer needs — the
character grid and one RGB triple per cell — and emit them as compact strings.

    python3 tools/build-ascii-scene.py asciinator_3Aug_001.html
"""
import base64
import html
import json
import re
import sys
from pathlib import Path

SPAN = re.compile(r'<span style="color:#([0-9a-fA-F]{6})">(.*?)</span>', re.S)

def main(src, dest):
    doc = Path(src).read_text(encoding='utf-8', errors='replace')
    body = doc[doc.index('<pre'):]
    body = body[body.index('>') + 1:body.index('</pre>')]

    # Walk the markup keeping each cell's char and colour together. Text
    # *between* spans matters as much as the spans themselves: an export of a
    # cut-out image leaves uncoloured spaces, and dropping them silently shifts
    # every later character in the row and skews the whole image.
    rows, row = [], []
    pos = 0

    def emit(text, rgb):
        nonlocal row
        for ch in text:
            if ch == '\n':
                rows.append(row)
                row = []
            else:
                row.append((ch, rgb))

    for m in SPAN.finditer(body):
        emit(html.unescape(body[pos:m.start()]), (0, 0, 0))
        rgb = tuple(int(m.group(1)[i:i + 2], 16) for i in (0, 2, 4))
        emit(html.unescape(m.group(2)), rgb)
        pos = m.end()
    emit(html.unescape(body[pos:]), (0, 0, 0))
    if row:
        rows.append(row)

    cols = max(len(r) for r in rows)
    # Pad short rows so the grid is rectangular; padding is blank and black,
    # which the renderer skips along with any other blank.
    text, colors = [], bytearray()
    for r in rows:
        padded = r + [(' ', (0, 0, 0))] * (cols - len(r))
        text.append(''.join(ch for ch, _ in padded))
        for _, (cr, cg, cb) in padded:
            colors += bytes((cr, cg, cb))

    js = (
        '/* Generated by tools/build-ascii-scene.py — do not edit by hand. */\n'
        'window.ASCII_SCENE = {\n'
        f'  cols: {cols},\n'
        f'  rows: {len(rows)},\n'
        f'  chars: {json.dumps("".join(text))},\n'
        f'  rgb: "{base64.b64encode(colors).decode()}",\n'
        '};\n'
    )

    Path(dest).write_text(js, encoding='utf-8')
    print(f'{cols}x{len(rows)} cells -> {dest} ({Path(dest).stat().st_size/1024:.0f} KB)')

if __name__ == '__main__':
    src = sys.argv[1] if len(sys.argv) > 1 else 'asciinator_3Aug_001.html'
    dest = sys.argv[2] if len(sys.argv) > 2 else 'site/js/ascii-scene.js'
    main(src, dest)
