#!/usr/bin/env python3
"""Convert a source image straight into site/js/ascii-scene.js at any density.

The ASCIInator export is fixed at 220 columns, which is the ceiling on how much
detail the background can show. Going back to the original photo lets us pick
the grid size. The renderer only ever uses each cell's luminance (it re-colours
everything through its own blue ramp), so we store one byte per cell instead of
an RGB triple — half the payload of the old format at twice the density.

    python3 tools/image-to-ascii.py asciinator_3Aug_003.png 400

Cells are sampled with the renderer's 1.98 height:width ratio so the scene keeps
its proportions.
"""
import base64
import json
import sys
from pathlib import Path

from PIL import Image

ASPECT = 1.188 / 0.6          # cell height / width, matches ascii-bg.js
# Sparse -> dense, tracking dark -> bright. No space in the ramp: the renderer
# skips blank cells, and a space for the darkest water would punch holes in the
# grid instead of rendering it as a deep navy field.
RAMP = '.:-~=+*#%@'


ALPHA_MIN = 40                # below this a cell is background, not an animal


def main(src, cols, dest):
    img = Image.open(src).convert('RGBA')
    rows = max(1, round(img.height / img.width * cols / ASPECT))
    small = img.resize((cols, rows), Image.LANCZOS)
    px = small.load()

    # Value (max channel), not Rec.709 luminance: this scene is almost entirely
    # blue, and luminance weights blue at 0.07, which crushes it to near-black.
    # A cut-out PNG carries its own mask, so alpha decides what gets drawn at
    # all — far cleaner than thresholding on brightness.
    raw, alpha = [], []
    for y in range(rows):
        for x in range(cols):
            r, g, b, a = px[x, y]
            raw.append(max(r, g, b))
            alpha.append(a)

    # Stretch to the full byte range over the visible cells only, clipping the
    # tails, so the renderer's ramp gets used end to end.
    visible = sorted(v for v, a in zip(raw, alpha) if a >= ALPHA_MIN) or raw
    lo = visible[int(len(visible) * 0.02)]
    hi = visible[int(len(visible) * 0.98)]
    span = max(1, hi - lo)

    chars, lum = [], bytearray()
    for v, a in zip(raw, alpha):
        if a < ALPHA_MIN:
            lum.append(0)
            chars.append(' ')          # the renderer skips blanks entirely
            continue
        n = min(255, max(0, round((v - lo) / span * 255)))
        # Fade the ramp out across the cut-out's soft edges.
        if a < 255:
            n = round(n * a / 255)
        lum.append(n)
        chars.append(RAMP[min(len(RAMP) - 1, n * len(RAMP) // 256)])

    js = (
        '/* Generated by tools/image-to-ascii.py — do not edit by hand. */\n'
        'window.ASCII_SCENE = {\n'
        f'  cols: {cols},\n'
        f'  rows: {rows},\n'
        f'  chars: {json.dumps("".join(chars))},\n'
        f'  lum: "{base64.b64encode(lum).decode()}",\n'
        '};\n'
    )
    Path(dest).write_text(js, encoding='utf-8')
    kb = Path(dest).stat().st_size / 1024
    print(f'{cols}x{rows} = {cols * rows} cells -> {dest} ({kb:.0f} KB)')


if __name__ == '__main__':
    src = sys.argv[1]
    cols = int(sys.argv[2]) if len(sys.argv) > 2 else 400
    dest = sys.argv[3] if len(sys.argv) > 3 else 'site/js/ascii-scene.js'
    main(src, cols, dest)
